apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: telemetry
resources:
  - ../../base
  - ../../otel/agent
  - ../../otel/gateway
  - ../../buffering
  - ../../processing
  - ../../storage
secretGenerator:
  - name: telemetry-object-storage
    literals:
      - MINIO_ACCESS_KEY=aria-local
      - MINIO_SECRET_KEY=replace-before-shared-use
generatorOptions: {disableNameSuffixHash: true}
