apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tenants.yaml
  - quotas.yaml
  - network-policies.yaml
  - service-accounts.yaml
commonLabels:
  app.kubernetes.io/part-of: aria-ai-factory
