apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-workload
  namespace: ai-team-blue
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-workload
  namespace: ai-team-gold
automountServiceAccountToken: false
