apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-readonly-root-filesystem
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: readonly-rootfs
      match:
        any:
          - resources:
              kinds: ["Pod"]
      validate:
        message: "Containers should use readOnlyRootFilesystem where possible."
        pattern:
          spec:
            containers:
              - securityContext:
                  readOnlyRootFilesystem: true
