apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: payments-api-db
  namespace: payments
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-platform-store
    kind: ClusterSecretStore
  target:
    name: payments-api-db
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: kv/payments-api/database
        property: username
    - secretKey: password
      remoteRef:
        key: kv/payments-api/database
        property: password
