from __future__ import annotations
from dataclasses import dataclass, field
from server.gitops_ai.patch_generator import PatchGenerator
from server.gitops_ai.pr_generator import PullRequestGenerator

@dataclass
class GitOpsRemediationService:
    patcher: PatchGenerator = field(default_factory=PatchGenerator)
    pr_generator: PullRequestGenerator = field(default_factory=PullRequestGenerator)

    def propose(self, service: str, issue: str, dry_run: bool = True) -> dict:
        patches = [self.patcher.helm_values_patch(service, issue)]
        if "rollback" in issue.lower() or "deployment" in issue.lower():
            patches.append(self.patcher.rollback_patch(service))
        pr = self.pr_generator.create(
            title=f"ARIA remediation for {service}: {issue}",
            body="Generated by ARIA. This PR requires human review, ReBAC authorization, policy validation, and approval before merge.",
            files=patches,
            dry_run=dry_run,
        )
        return {
            "service": service,
            "issue": issue,
            "patches": patches,
            "pull_request": pr,
            "safety_boundary": "AI proposes GitOps changes only; it cannot merge or sync directly.",
        }
