apiVersion: aigateway.envoyproxy.io/v1beta1
kind: AIGatewayRoute
metadata:
  name: aria-private-model
  namespace: ai-gateway
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: aria-ai-gateway
  schema:
    name: OpenAI
  rules:
    - matches:
        - headers:
            - type: Exact
              name: x-ai-eg-model
              value: aria-private
      backendRefs:
        - name: aria-vllm
          modelNameOverride: aria-private
  llmRequestCosts:
    - metadataKey: llm_total_token
      type: TotalToken
