apiVersion: apps/v1
kind: Deployment
metadata:
  name: aria-api
  labels:
    app: aria-api
    owner: platform
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: aria-api
  template:
    metadata:
      labels:
        app: aria-api
        owner: platform
    spec:
      containers:
        - name: aria-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
