apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-api
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: checkout-api
  template:
    metadata:
      labels:
        app: checkout-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: checkout-api
          image: checkout-api:local
          imagePullPolicy: Never
          ports:
            - containerPort: 9000
          env:
            - name: CHAOS_LATENCY_MS
              value: "0"
            - name: CHAOS_ERROR_RATE
              value: "0"
            - name: INVENTORY_URL
              value: http://inventory-api.demo.svc.cluster.local:9100
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: otel-gateway.telemetry.svc.cluster.local:4317
            - name: OTEL_PROPAGATORS
              value: tracecontext,baggage
          readinessProbe:
            httpGet:
              path: /health
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  name: checkout-api
  namespace: demo
  labels:
    app: checkout-api
spec:
  selector:
    app: checkout-api
  ports:
    - name: http
      port: 9000
      targetPort: 9000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata: {name: checkout-api, namespace: demo, labels: {release: kube-prometheus-stack}}
spec:
  selector: {matchLabels: {app: checkout-api}}
  endpoints: [{port: http, path: /metrics, interval: 15s}]
