from server.platform.kubernetes_internals.etcd_backup import EtcdBackupInspector
from server.platform.kubernetes_internals.control_plane_health import ControlPlaneHealthInspector
from server.platform.kubernetes_internals.admission_health import AdmissionWebhookInspector
from server.platform.kubernetes_internals.coredns_health import CoreDnsHealthInspector
from server.platform.kubernetes_internals.cni_health import CniHealthInspector
from server.platform.kubernetes_internals.cluster_restore_validator import ClusterRestoreValidator
from server.platform.kubernetes_internals.upgrade_readiness import UpgradeReadinessInspector
